name = "katelyatv"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
NEXT_PUBLIC_STORAGE_TYPE = local
USERNAME = "admin"
AUTH_PASSWORD = "88888888"
